// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmbcStatusBoard.Api.Data;

#nullable disable

namespace SmbcStatusBoard.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629031114_AddChurches")]
    partial class AddChurches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeriodEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearlyAllocatedAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalaryUserId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetCategoryAmountHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("BudgetCategoryAmountHistories");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DebtId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("DebtId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("BudgetEntries");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("BudgetTypeOrders");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckInToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckInToken")
                        .IsUnique()
                        .HasFilter("[CheckInToken] IS NOT NULL");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ClassId", "ChildId", "SessionDate")
                        .IsUnique();

                    b.ToTable("ChildAttendances");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckedInByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CheckedOutByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckedInByUserId");

                    b.HasIndex("CheckedOutByUserId");

                    b.HasIndex("ChildId");

                    b.ToTable("ChildCheckIns");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildLinkSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestingUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestedChildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewChildId");

                    b.HasIndex("RequestingUserId");

                    b.HasIndex("SuggestedChildId");

                    b.ToTable("ChildLinkSuggestions");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Churches");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromotionClassId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresChildPass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromotionClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassId", "UserId", "SessionDate")
                        .IsUnique();

                    b.ToTable("ClassAttendances");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassChildren");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteLastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassMembers");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanTermMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthsIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.DebtPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExtraPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("DebtPayments");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EventPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHeroImage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("EventPhotos");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.GivingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BudgetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("GivingEntries");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.InviteToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InviteTokens");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BenevolenceData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChurchEventData")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ministry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Urgency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BudgetDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ministry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OneDriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.RoleTimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleTimeSlots");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.SpecialEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpecialEvents");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.SpecialEventTimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialEventId");

                    b.ToTable("SpecialEventTimeSlots");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedItemTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JoinedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MembershipDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SalaryDonateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryDonateGivingCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalaryDonatePercentage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpouseUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SalaryDonateGivingCategoryId");

                    b.HasIndex("SpouseUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.VolunteerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SundayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResponseToken")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("VolunteerAssignments");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.VolunteerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecialEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorshipServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecialEventId");

                    b.HasIndex("WorshipServiceTypeId");

                    b.ToTable("VolunteerRoles");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("WorshipPlans");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("SongId");

                    b.ToTable("WorshipPlanItems");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlanSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("WorshipPlanSections");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorshipServiceTypes");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PraiseChartsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PraiseChartsSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("PraiseChartsThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorshipSongs");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetCategory", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "SalaryUser")
                        .WithMany()
                        .HasForeignKey("SalaryUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SalaryUser");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetCategoryAmountHistory", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.BudgetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetEntry", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.BudgetCategory", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.Debt", "Debt")
                        .WithMany()
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Debt");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Child", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "ParentUser")
                        .WithMany("Children")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedUser");

                    b.Navigation("ParentUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildAttendance", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.Class", "Class")
                        .WithMany("ChildAttendance")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildCheckIn", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "CheckedInByUser")
                        .WithMany()
                        .HasForeignKey("CheckedInByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "CheckedOutByUser")
                        .WithMany()
                        .HasForeignKey("CheckedOutByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedInByUser");

                    b.Navigation("CheckedOutByUser");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ChildLinkSuggestion", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "NewChild")
                        .WithMany()
                        .HasForeignKey("NewChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "RequestingUser")
                        .WithMany()
                        .HasForeignKey("RequestingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "SuggestedChild")
                        .WithMany()
                        .HasForeignKey("SuggestedChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewChild");

                    b.Navigation("RequestingUser");

                    b.Navigation("SuggestedChild");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Class", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Class", "PromotionClass")
                        .WithMany()
                        .HasForeignKey("PromotionClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PromotionClass");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassAttendance", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Class", "Class")
                        .WithMany("Attendance")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassChild", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "Child")
                        .WithMany("ClassChildren")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.Class", "Class")
                        .WithMany("ClassChildren")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.ClassMember", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Class", "Class")
                        .WithMany("Members")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Debt", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.BudgetCategory", "BudgetCategory")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BudgetCategory");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.DebtPayment", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Debt", "Debt")
                        .WithMany("Payments")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EventPhoto", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Item", "Item")
                        .WithMany("EventPhotos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.EventRegistration", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmbcStatusBoard.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Child");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.GivingEntry", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.BudgetCategory", "BudgetCategory")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany("GivingEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.InviteToken", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany("InviteTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Item", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.RoleTimeSlot", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.VolunteerRole", "Role")
                        .WithMany("TimeSlots")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.SpecialEventTimeSlot", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.SpecialEvent", "SpecialEvent")
                        .WithMany("TimeSlots")
                        .HasForeignKey("SpecialEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialEvent");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.User", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.Church", "Church")
                        .WithMany("Users")
                        .HasForeignKey("ChurchId");

                    b.HasOne("SmbcStatusBoard.Api.Models.BudgetCategory", "SalaryDonateGivingCategory")
                        .WithMany()
                        .HasForeignKey("SalaryDonateGivingCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("SalaryDonateGivingCategory");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.UserPreference", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.VolunteerAssignment", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.VolunteerRole", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.VolunteerRole", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.SpecialEvent", "SpecialEvent")
                        .WithMany()
                        .HasForeignKey("SpecialEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmbcStatusBoard.Api.Models.WorshipServiceType", "WorshipServiceType")
                        .WithMany("VolunteerRoles")
                        .HasForeignKey("WorshipServiceTypeId");

                    b.Navigation("SpecialEvent");

                    b.Navigation("WorshipServiceType");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlan", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.WorshipServiceType", "ServiceType")
                        .WithMany("Plans")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlanItem", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.WorshipPlanSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmbcStatusBoard.Api.Models.WorshipSong", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("Section");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlanSection", b =>
                {
                    b.HasOne("SmbcStatusBoard.Api.Models.WorshipPlan", "Plan")
                        .WithMany("Sections")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.BudgetCategory", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Child", b =>
                {
                    b.Navigation("ClassChildren");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Church", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Class", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("ChildAttendance");

                    b.Navigation("ClassChildren");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Debt", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.Item", b =>
                {
                    b.Navigation("EventPhotos");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.SpecialEvent", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("GivingEntries");

                    b.Navigation("InviteTokens");

                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.VolunteerRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlan", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipPlanSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SmbcStatusBoard.Api.Models.WorshipServiceType", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("VolunteerRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
